
state_list = ["OFF",
              "HOME","MOVING","IDLE","IDLE-BORDER","MOVING-BODER"
              "PRE-PICK","PICKING",
              "PRE-PLACE","PLACING","RETURNING"]
#OFF -> HOME
#HOME -> MOVING
#MOVING <> IDLE
#MOVING -> IDLE-BORDER
#IDLE-BORDER <> MOVING-BODER
#MOVING-BODER -> MOVING
#MOVING <> PRE-PICK
#PRE-PICK -> PICKING
#PICKING -> PRE-PLACE
#PRE-PLACE -> PLACING
#PLACING -> RETURNING -> HOME
